#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-model-deployment
spec:
  selector:
    matchLabels:
      app: diabetes-model-server
  replicas: 1
  template:
    metadata:
      labels:
        app: diabetes-model-server
    spec:
      containers:
      - name: diabetes-model-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/aldotr/diabetes-model-ai:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: diabetes-model-service
  name: diabetes-model-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: diabetes-model-server
  type: LoadBalancer
