#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetesml-deployment
spec:
  selector:
    matchLabels:
      app: diabetesml-server
  replicas: 1
  template:
    metadata:
      labels:
        app: diabetesml-server
    spec:
      containers:
      - name: diabetesml-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/codigyx/diabetes-ml:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: diabetesml-service
  name: diabetesml-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: diabetesml-server
  type: LoadBalancer